### ISSUE TITLE
event emails' text/plain part missing URLs

### ISSUE THREAD

**Issue by jidanni** [osmus/mappingusa.org-redirects#2]
I'm sorry I don't know where to put mappingUSA bugs so I'll put them
here.

Let's take a look at the text/plain part of the event emails.
```
Date: Fri, 19 Jan 2024 18:50:07 +0000 (UTC)
From: OpenStreetMap US <events@openstreetmap.us>
...
Content-Type: text/plain; charset=utf-8
...
Via browser: Click the button below. If prompted enter the password: *****

Friday Join Link
Saturday Join Information
```

Well we see that without the URLs added to the text/plain rendering of
the HTML part... well, you might as well not include the text/plain part.
@quincylvania

**Comment by quincylvania** [comment]
@jidanni We had some issues with out email provider this year. I'm glad you were able to join nonetheless.
