### ISSUE TITLE
Breakout sessions also need bathroom breaks

### ISSUE THREAD

**Issue by jidanni** [osmus/mappingusa.org-redirects#3]
I'm sorry I don't know where to put mappingUSA bugs so I'll put them
here.

On the second day there were no bathroom breaks between sessions. Hope they will be included next year.

@mcawley : please also see the other issues I filed here in https://github.com/osmus/mappingusa.org-redirects/issues . Thanks!

**Comment by quincylvania** [comment]
@jidanni Thanks for the feedback.
