### ISSUE TITLE
Red timeline indicator gone on second day

### ISSUE THREAD

**Issue by jidanni** [osmus/mappingusa.org-redirects#4]
On the first day, on
https://openstreetmap.us/events/mapping-usa/
there was a neat red line showing the current place we were at.
(It moved down the list as the hours went by.)

But on the second day the red line was gone.

(Yes, we could just look at a clock and figure it out ourselves.)
@quincylvania (who probably is buried in work and does not see these.)

**Comment by quincylvania** [comment]
@jidanni Yes, the second day was a basic HTML table. We might adjust this for the next conference but it's not a big deal either way.
